fizato

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,7 +10,7 @@ on:
 permissions:
   contents: read
   packages: write
-
+omega
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -129,9 +129,7 @@ jobs:
                 git pull || { echo '[REMOTE] ERRORE: git pull fallito'; exit 1; }
               else
                 echo '[REMOTE] omega-app NON è una git repo, la elimino e faccio git clone...'
-                rm -rf omega-app
-                git clone https://github.com/davidepatrucco/omega-components-tracker.git omega-app || { echo '[REMOTE] ERRORE: git clone fallito'; exit 1; }
-                cd omega-app
+                git clone https://github.com/davidepatrucco/omega-components-tracker.git omega-components-tracker || { echo '[REMOTE] ERRORE: git clone fallito'; exit 1; }
               fi
             echo '[REMOTE] Login a ECR...'
             export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
@@ -142,7 +140,7 @@ jobs:
             echo '[REMOTE] Eseguo login a docker...'
             aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 152485877259.dkr.ecr.us-east-1.amazonaws.com || { echo '[REMOTE] ERRORE: docker login fallito'; exit 1; }
 
-            cd /home/$SSH_USER/omega-app/infra
+            cd /home/$SSH_USER/omega-components-tracker/omega-app/infra
             if docker compose version >/dev/null 2>&1; then
               echo '[REMOTE] Pull immagini Docker...'
               sudo docker compose -f docker-compose.lightsail.yml pull
